/* 🤖 this file was generated by svg-to-ts*/

import { CountryFlagIcon } from './icons-data.model';

export const countryFlagIconMm: CountryFlagIcon = {
  name: 'mm',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 640 480"><defs><path id="MM_svg__a" fill="#fff" d="M0-.5l.2.5h-.4z" transform="scale(8.844)"/><g id="MM_svg__b"><use width="18" height="12" transform="rotate(-144)" xlink:href="#MM_svg__a"/><use width="18" height="12" transform="rotate(-72)" xlink:href="#MM_svg__a"/><use width="18" height="12" xlink:href="#MM_svg__a"/><use width="18" height="12" transform="rotate(72)" xlink:href="#MM_svg__a"/><use width="18" height="12" transform="rotate(144)" xlink:href="#MM_svg__a"/></g></defs><path fill="#fecb00" d="M0-.1h640V160H0z"/><path fill="#ea2839" d="M0 320h640v160H0z"/><path fill="#34b233" d="M0 160h640v160H0z"/><use width="18" height="12" x="9" y="6.4" transform="matrix(40 0 0 40 -40 0)" xlink:href="#MM_svg__b"/></svg>`
};
