/* 🤖 this file was generated by svg-to-ts*/

import { CountryFlagIcon } from './icons-data.model';

export const countryFlagIconVe: CountryFlagIcon = {
  name: 've',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 640 480"><defs><g id="VE_svg__d" transform="translate(0 -36)"><g id="VE_svg__c"><g id="VE_svg__b"><path id="VE_svg__a" fill="#fff" d="M0-5L-1.5-.2l2.8.9z"/><use width="180" height="120" transform="scale(-1 1)" xlink:href="#VE_svg__a"/></g><use width="180" height="120" transform="rotate(72)" xlink:href="#VE_svg__b"/></g><use width="180" height="120" transform="rotate(-72)" xlink:href="#VE_svg__b"/><use width="180" height="120" transform="rotate(144)" xlink:href="#VE_svg__c"/></g></defs><path fill="#cf142b" d="M0 0h640v480H0z"/><path fill="#00247d" d="M0 0h640v320H0z"/><path fill="#fc0" d="M0 0h640v160H0z"/><g id="VE_svg__f" transform="matrix(4 0 0 4 320 336)"><g id="VE_svg__e"><use width="180" height="120" transform="rotate(10)" xlink:href="#VE_svg__d"/><use width="180" height="120" transform="rotate(30)" xlink:href="#VE_svg__d"/></g><use width="180" height="120" transform="rotate(40)" xlink:href="#VE_svg__e"/></g><use width="180" height="120" transform="rotate(-80 320 336)" xlink:href="#VE_svg__f"/></svg>`
};
