/* 🤖 this file was generated by svg-to-ts*/

import { CountryFlagIcon } from './icons-data.model';

export const countryFlagIconEu: CountryFlagIcon = {
  name: 'eu',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 640 480"><defs><g id="EU_svg__d"><g id="EU_svg__b"><path id="EU_svg__a" d="M0-1l-.3 1 .5.1z"/><use transform="scale(-1 1)" xlink:href="#EU_svg__a"/></g><g id="EU_svg__c"><use transform="rotate(72)" xlink:href="#EU_svg__b"/><use transform="rotate(144)" xlink:href="#EU_svg__b"/></g><use transform="scale(-1 1)" xlink:href="#EU_svg__c"/></g></defs><path fill="#039" d="M0 0h640v480H0z"/><g fill="#fc0" transform="translate(320 242.3) scale(23.7037)"><use width="100%" height="100%" y="-6" xlink:href="#EU_svg__d"/><use width="100%" height="100%" y="6" xlink:href="#EU_svg__d"/><g id="EU_svg__e"><use width="100%" height="100%" x="-6" xlink:href="#EU_svg__d"/><use width="100%" height="100%" transform="rotate(-144 -2.3 -2.1)" xlink:href="#EU_svg__d"/><use width="100%" height="100%" transform="rotate(144 -2.1 -2.3)" xlink:href="#EU_svg__d"/><use width="100%" height="100%" transform="rotate(72 -4.7 -2)" xlink:href="#EU_svg__d"/><use width="100%" height="100%" transform="rotate(72 -5 .5)" xlink:href="#EU_svg__d"/></g><use width="100%" height="100%" transform="scale(-1 1)" xlink:href="#EU_svg__e"/></g></svg>`
};
