import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  countryFlagIconAo,
  countryFlagIconBf,
  countryFlagIconBi,
  countryFlagIconBj,
  countryFlagIconBw,
  countryFlagIconCd,
  countryFlagIconCf,
  countryFlagIconCg,
  countryFlagIconCi,
  countryFlagIconCm,
  countryFlagIconCv,
  countryFlagIconDj,
  countryFlagIconDz,
  countryFlagIconEg,
  countryFlagIconEh,
  countryFlagIconEr,
  countryFlagIconEt,
  countryFlagIconGa,
  countryFlagIconGh,
  countryFlagIconGm,
  countryFlagIconGn,
  countryFlagIconGq,
  countryFlagIconGw,
  countryFlagIconKe,
  countryFlagIconKm,
  countryFlagIconLr,
  countryFlagIconLs,
  countryFlagIconLy,
  countryFlagIconMa,
  countryFlagIconMg,
  countryFlagIconMl,
  countryFlagIconMr,
  countryFlagIconMu,
  countryFlagIconMw,
  countryFlagIconMz,
  countryFlagIconNa,
  countryFlagIconNe,
  countryFlagIconNg,
  countryFlagIconRw,
  countryFlagIconSc,
  countryFlagIconSd,
  countryFlagIconSl,
  countryFlagIconSn,
  countryFlagIconSo,
  countryFlagIconSs,
  countryFlagIconSt,
  countryFlagIconSz,
  countryFlagIconTd,
  countryFlagIconTg,
  countryFlagIconTn,
  countryFlagIconTz,
  countryFlagIconUg,
  countryFlagIconZa,
  countryFlagIconZm,
  countryFlagIconZw,
  NgxCountryFlagIconsTwemojiModule,
  NgxCountryFlagIconsTwemojiService,
} from '@kingdarboja/ngx-country-flag-icons-twemoji';

import { AfricaComponent } from './africa.component';
import { AfricaRoutingModule } from './africa.routing';

@NgModule({
  declarations: [AfricaComponent],
  imports: [
    CommonModule,
    AfricaRoutingModule,
    NgxCountryFlagIconsTwemojiModule,
  ],
})
export class AfricaModule {
  constructor(
    private countryFlagIconsService: NgxCountryFlagIconsTwemojiService
  ) {
    this.countryFlagIconsService.registerIcons([
      countryFlagIconDz,
      countryFlagIconAo,
      countryFlagIconBj,
      countryFlagIconBw,
      countryFlagIconBf,
      countryFlagIconBi,
      countryFlagIconCv,
      countryFlagIconCm,
      countryFlagIconCf,
      countryFlagIconTd,
      countryFlagIconKm,
      countryFlagIconCg,
      countryFlagIconCd,
      countryFlagIconCi,
      countryFlagIconDj,
      countryFlagIconEg,
      countryFlagIconGq,
      countryFlagIconEr,
      countryFlagIconSz,
      countryFlagIconEt,
      countryFlagIconGa,
      countryFlagIconGm,
      countryFlagIconGh,
      countryFlagIconGn,
      countryFlagIconGw,
      countryFlagIconKe,
      countryFlagIconLs,
      countryFlagIconLr,
      countryFlagIconLy,
      countryFlagIconMg,
      countryFlagIconMw,
      countryFlagIconMl,
      countryFlagIconMr,
      countryFlagIconMu,
      countryFlagIconMa,
      countryFlagIconMz,
      countryFlagIconNa,
      countryFlagIconNe,
      countryFlagIconNg,
      countryFlagIconRw,
      countryFlagIconSt,
      countryFlagIconSn,
      countryFlagIconSc,
      countryFlagIconSl,
      countryFlagIconSo,
      countryFlagIconZa,
      countryFlagIconSs,
      countryFlagIconSd,
      countryFlagIconTz,
      countryFlagIconTg,
      countryFlagIconTn,
      countryFlagIconUg,
      countryFlagIconEh,
      countryFlagIconZm,
      countryFlagIconZw,
    ]);
  }
}
