/* 🤖 this file was generated by svg-to-ts*/

import { CountryFlagIcon } from './icons-data.model';

export const countryFlagIconGw: CountryFlagIcon = {
  name: 'gw',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 640 480"><path fill="#ce1126" d="M0 0h220v480H0z"/><path fill="#fcd116" d="M220 0h420v240H220z"/><path fill="#009e49" d="M220 240h420v240H220z"/><g id="GW_svg__b" transform="matrix(80 0 0 80 110 240)"><path id="GW_svg__a" d="M0-1v1h.5" transform="rotate(18 0 -1)"/><use width="100%" height="100%" transform="scale(-1 1)" xlink:href="#GW_svg__a"/></g><use width="100%" height="100%" transform="rotate(72 110 240)" xlink:href="#GW_svg__b"/><use width="100%" height="100%" transform="rotate(144 110 240)" xlink:href="#GW_svg__b"/><use width="100%" height="100%" transform="rotate(-144 110 240)" xlink:href="#GW_svg__b"/><use width="100%" height="100%" transform="rotate(-72 110 240)" xlink:href="#GW_svg__b"/></svg>`
};
