/* 🤖 this file was generated by svg-to-ts*/

import { CountryFlagIcon } from './icons-data.model';

export const countryFlagIconHn: CountryFlagIcon = {
  name: 'hn',
  data: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 640 480"><path fill="#0073cf" d="M0 0h640v480H0z"/><path fill="#fff" d="M0 160h640v160H0z"/><g id="HN_svg__c" fill="#0073cf" transform="translate(320 240) scale(26.66665)"><g id="HN_svg__b"><path id="HN_svg__a" d="M-.3 0l.5.1L0-1z"/><use width="100%" height="100%" transform="scale(-1 1)" xlink:href="#HN_svg__a"/></g><use width="100%" height="100%" transform="rotate(72)" xlink:href="#HN_svg__b"/><use width="100%" height="100%" transform="rotate(-72)" xlink:href="#HN_svg__b"/><use width="100%" height="100%" transform="rotate(144)" xlink:href="#HN_svg__b"/><use width="100%" height="100%" transform="rotate(-144)" xlink:href="#HN_svg__b"/></g><use width="100%" height="100%" transform="translate(133.3 -42.7)" xlink:href="#HN_svg__c"/><use width="100%" height="100%" transform="translate(133.3 37.3)" xlink:href="#HN_svg__c"/><use width="100%" height="100%" transform="translate(-133.3 -42.7)" xlink:href="#HN_svg__c"/><use width="100%" height="100%" transform="translate(-133.3 37.3)" xlink:href="#HN_svg__c"/></svg>`
};
