import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  countryFlagIconAo,
  countryFlagIconBf,
  countryFlagIconBi,
  countryFlagIconBj,
  countryFlagIconBw,
  countryFlagIconCd,
  countryFlagIconCf,
  countryFlagIconCg,
  countryFlagIconCi,
  countryFlagIconCm,
  countryFlagIconCv,
  countryFlagIconDj,
  countryFlagIconDz,
  countryFlagIconEg,
  countryFlagIconEh,
  countryFlagIconEr,
  countryFlagIconEt,
  countryFlagIconGa,
  countryFlagIconGh,
  countryFlagIconGm,
  countryFlagIconGn,
  countryFlagIconGq,
  countryFlagIconGw,
  countryFlagIconKe,
  countryFlagIconKm,
  countryFlagIconLr,
  countryFlagIconLs,
  countryFlagIconLy,
  countryFlagIconMa,
  countryFlagIconMg,
  countryFlagIconMl,
  countryFlagIconMr,
  countryFlagIconMu,
  countryFlagIconMw,
  countryFlagIconMz,
  countryFlagIconNa,
  countryFlagIconNe,
  countryFlagIconNg,
  countryFlagIconRw,
  countryFlagIconSc,
  countryFlagIconSd,
  countryFlagIconSl,
  countryFlagIconSn,
  countryFlagIconSo,
  countryFlagIconSs,
  countryFlagIconSt,
  countryFlagIconSz,
  countryFlagIconTd,
  countryFlagIconTg,
  countryFlagIconTn,
  countryFlagIconTz,
  countryFlagIconUg,
  countryFlagIconZa,
  countryFlagIconZm,
  countryFlagIconZw,
  NgxCountryFlagIconsLipisModule,
  NgxCountryFlagIconsLipisService,
} from '@kingdarboja/ngx-country-flag-icons-lipis';

import { AfricaComponent } from './africa.component';
import { AfricaRoutingModule } from './africa.routing';

@NgModule({
  declarations: [AfricaComponent],
  imports: [CommonModule, AfricaRoutingModule, NgxCountryFlagIconsLipisModule],
})
export class AfricaModule {
  constructor(
    private countryFlagIconsService: NgxCountryFlagIconsLipisService
  ) {
    this.countryFlagIconsService.registerIcons([
      countryFlagIconAo,
      countryFlagIconBf,
      countryFlagIconBi,
      countryFlagIconBj,
      countryFlagIconBw,
      countryFlagIconCd,
      countryFlagIconCf,
      countryFlagIconCg,
      countryFlagIconCi,
      countryFlagIconCm,
      countryFlagIconCv,
      countryFlagIconDj,
      countryFlagIconDz,
      countryFlagIconEg,
      countryFlagIconEh,
      countryFlagIconEr,
      countryFlagIconEt,
      countryFlagIconGa,
      countryFlagIconGh,
      countryFlagIconGm,
      countryFlagIconGn,
      countryFlagIconGq,
      countryFlagIconGw,
      countryFlagIconKe,
      countryFlagIconKm,
      countryFlagIconLr,
      countryFlagIconLs,
      countryFlagIconLy,
      countryFlagIconMa,
      countryFlagIconMg,
      countryFlagIconMl,
      countryFlagIconMr,
      countryFlagIconMu,
      countryFlagIconMw,
      countryFlagIconMz,
      countryFlagIconNa,
      countryFlagIconNe,
      countryFlagIconNg,
      countryFlagIconRw,
      countryFlagIconSc,
      countryFlagIconSd,
      countryFlagIconSl,
      countryFlagIconSn,
      countryFlagIconSo,
      countryFlagIconSs,
      countryFlagIconSt,
      countryFlagIconSz,
      countryFlagIconTd,
      countryFlagIconTg,
      countryFlagIconTn,
      countryFlagIconTz,
      countryFlagIconUg,
      countryFlagIconZa,
      countryFlagIconZm,
      countryFlagIconZw,
    ]);
  }
}
